
server:
  port: 8080

spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    com.altradar: DEBUG
upbit:
  accessKey: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  markets:
    - KRW-BTC
    - KRW-ETH
    - KRW-XRP
  api:
    candle-url: "https://api.upbit.com/v1/candles/minutes/1?market=%s&count=200"
    ticker-url: "https://api.upbit.com/v1/ticker?markets=%s"
  refresh-interval-seconds: 10
